train_imgs_dir: asdsad
train_anns: asdasd
val_imgs_dir: asdasd
val_anns: ''
test_imgs_dir: ''
test_anns: ''
infer_imgs_dir: ''
save_dir: ''
task: ''
batch_size: ''
class_agnostic_weights: ''
classes: ''
dropout: ''
joint_probability: ''
infer_display_thresh: ''
nms_thresh: ''
offset: ''
refresh_rate: ''
resume_training: ''
resume_weights: ''
sampler: ''
sparse: ''
supervised: ''
viz_test_batches: ''
weights: ''
workers: ''
lr_backbone: ''
lr_detr: ''
lr_drop: ''
lr_mil: ''
lr_patience: ''
lr_step_size: ''
objectness_scale: ''
weight_decay: ''
activation: ''
dec_layers: ''
dec_points: ''
dilation: ''
enc_layers: ''
enc_points: ''
feature_levels: ''
feedforward_dim: ''
hidden_dim: ''
heads: ''
position_embedding: ''
position_embedding_scale: ''
queries: ''
accumulate_grad_batches: ''
deterministic: ''
gpus: ''
max_epochs: ''
