train_imgs_dir: data/fsod/images
train_anns: data/fsod/annotations/fsod_200_train_seed0_trn0.8.json
val_imgs_dir: data/fsod/images
val_anns: data/fsod/annotations/fsod_200_test_seed0_trn0.8.json
test_imgs_dir: data/fsod/images
test_anns: data/fsod/annotations/fsod_200_test_seed0_trn0.8.json
infer_imgs_dir: ''
save_dir: out
task: infer
batch_size: '2'
class_agnostic_weights: ckpts/deformable-detr_fsod-800_class-agnostic_50epochs.pth
classes: '200'
dropout: '0.1'
joint_probability: '1'
infer_display_thresh: '0.2'
nms_thresh: '0.3'
offset: '1'
refresh_rate: '1'
resume_training: '0'
resume_weights: '0'
sampler: '0'
sparse: '1'
supervised: '0'
viz_test_batches: '20'
weights: ckpts/deformable-detr_fsod-800_50epochs.pth
workers: '4'
lr_backbone: 2e-5
lr_detr: 2e-4
lr_drop: '0.1'
lr_mil: 1e-3
lr_patience: '0'
lr_step_size: '15'
objectness_scale: '1000'
weight_decay: 1e-4
activation: relu
dec_layers: '6'
dec_points: '4'
dilation: '0'
enc_layers: '6'
enc_points: '4'
feature_levels: '4'
feedforward_dim: '1024'
hidden_dim: '256'
heads: '8'
position_embedding: sine
position_embedding_scale: '6.283185307179586'
queries: '300'
accumulate_grad_batches: '8'
deterministic: '1'
gpus: '1'
max_epochs: '1'
