train_imgs_dir: data/inaturalist/
train_anns: data/inaturalist/annotations/train_2017_bboxes_clean.json
val_imgs_dir: data/inaturalist/
val_anns: data/inaturalist/annotations/val_2017_bboxes_clean.json
test_imgs_dir: data/inaturalist/
test_anns: data/inaturalist/annotations/val_2017_bboxes_clean.json
infer_imgs_dir: ""
save_dir: ""

task: train

batch_size: 2
class_agnostic_weights: ckpts/deformable-detr_fsod-800_class-agnostic_50epochs.pth
classes: 2854
dropout: 0.1
joint_probability: True
infer_display_thresh: 0.2
nms_thresh: 0.3
offset: 0
refresh_rate: 1
resume_training: False
resume_weights: False
sampler: False
sparse: True
supervised: False
viz_test_batches: 20
weights: ckpts/deformable-detr_fsod-800_50epochs.pth
workers: 1

lr_backbone: 2e-5
lr_detr: 2e-4
lr_drop: 0.1
lr_mil: 1e-3
lr_patience: 0
lr_step_size: 6
objectness_scale: 1000
weight_decay: 1e-4

activation: "relu"
dec_layers: 6
dec_points: 4
dilation: False
enc_layers: 6
enc_points: 4
feature_levels: 4
feedforward_dim: 1024
hidden_dim: 256
heads: 8
position_embedding: "sine"
position_embedding_scale: 6.283185307179586 # 2Ï€ 
queries: 300

accumulate_grad_batches: 2
deterministic: True
gpus: 4
max_epochs: 10
